-- 유저, 학습 관련
SELECT * FROM USERS;
SELECT * FROM LEARNING;
SELECT * FROM SENTENCE;
SELECT * FROM FLASHCARD;
SELECT * FROM TOPIC;
-- 커뮤니티 관련
SELECT * FROM COMMUNITY_POST;
SELECT * FROM COMMUNITY_REPLY;
SELECT * FROM BOOKMARK;
SELECT * FROM LIKES;
-- 어드민, 고객센터 관련
SELECT * FROM BOARD_NOTICE;
SELECT * FROM BOARD_FAQ;
SELECT * FROM BOARD_QUESTION;
SELECT * FROM QUESTION_REPLY;
SELECT * FROM REPORT;

-- 유저, 학습 관련
DELETE FROM USERS WHERE 1 = 1;
DELETE FROM LEARNING WHERE 1 = 1;
DELETE FROM SENTENCE WHERE 1 = 1;
DELETE FROM FLASHCARD WHERE 1 = 1;
DELETE FROM TOPIC WHERE 1 = 1;
-- 커뮤니티 관련
DELETE FROM COMMUNITY_POST WHERE 1 = 1;
DELETE FROM COMMUNITY_REPLY WHERE 1 = 1;
DELETE FROM BOOKMARK WHERE 1 = 1;
DELETE FROM LIKES WHERE 1 = 1;
-- 어드민, 고객센터 관련
DELETE FROM BOARD_NOTICE WHERE 1 = 1;
DELETE FROM BOARD_FAQ WHERE 1 = 1;
DELETE FROM BOARD_QUESTION WHERE 1 = 1;
DELETE FROM QUESTION_REPLY WHERE 1 = 1;
DELETE FROM REPORT WHERE 1 = 1;
