select LEARNING_ID_SEQ.nextval into learning_id from dual;
insert into LEARNING (ID, USER_ID, LEARNING_TYPE, LEARNING_TEST_TYPE, LEARNING_TOPIC, LEARNING_DATE, LEARNING_LIKE)
VALUES (learning_id, 15, 'WRITING', null, 'The effects of social media on mental health and interpersonal relationships.', SYSDATE, '0');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'The effects of social media on mental health and interpersonal relationships.', 'The social media made us care about each other more than ever.', 'Social media has made us connect with each other more than ever.', 'Change "made" to "has made" to indicate that the impact is ongoing, and use "connect" instead of "care about" to convey the idea of social media bringing people together.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'The effects of social media on mental health and interpersonal relationships.', 'In result, It has effected our society a lot.', 'As a result, it has affected our society a lot.', 'Replace "In result" with "As a result" to show the cause-and-effect relationship, and use "affected" instead of "effected" to convey the idea of impact.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'The effects of social media on mental health and interpersonal relationships.', 'The politics have got to be more democratic but sometimes made too weak for wrong information and misinformation.', 'Politics need to be more democratic but sometimes are vulnerable to wrong information and misinformation.', 'Replace "got to be" with "need to be" to convey the idea of necessity, and use "vulnerable" instead of "weak" to convey the idea of susceptibility to misinformation.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'The effects of social media on mental health and interpersonal relationships.', 'That distorted information made people believe wrong fact and hate each other than necessary resulting into the missing of trust for each other.', 'Falsehoods made people believe in wrong things and hate each other more than necessary, resulting in a lack of trust for each other.', 'Replace "wrong fact" with "falsehoods" to convey the idea of deliberate misinformation, and use "resulted in" instead of "resulting into" to show the cause-and-effect relationship.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'The effects of social media on mental health and interpersonal relationships.', 'Furthermore, it made people know their relative position in economic hiarachy and caused them anxiety.', 'Moreover, it made people know their relative position in economic hierarchy and caused them anxiety.', 'Replace "Furthermore" with "Moreover" to add to the previous point, and use "hierarchy" instead of "hiarachy" to convey the correct spelling and meaning.');

select LEARNING_ID_SEQ.nextval into learning_id from dual;
insert into LEARNING (ID, USER_ID, LEARNING_TYPE, LEARNING_TEST_TYPE, LEARNING_TOPIC, LEARNING_DATE, LEARNING_LIKE)
VALUES (learning_id, 15, 'SPEAKING', 'TOEFL', 'What three qualities do you value most in a person, and why?', SYSDATE, '1');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'What three qualities do you value most in a person, and why?', 'I think the one is kindness and second is the ability for their job and finally the humbleness for them.', 'I believe that three important qualities are kindness, job ability, and humbleness.', 'The sentence is unclear and lacks parallel structure. It can be improved by rephrasing it to list the three qualities in a parallel structure.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'What three qualities do you value most in a person, and why?', 'I cannot tell the exact reason why I told that three personality about quality but in my experience I think it is.', 'I cannot explain the exact reason why I consider these three qualities important, but based on my experience, I believe they are crucial.', 'The sentence is unclear and lacks proper grammar. It can be improved by rephrasing it to clarify the meaning.');

select LEARNING_ID_SEQ.nextval into learning_id from dual;
insert into LEARNING (ID, USER_ID, LEARNING_TYPE, LEARNING_TEST_TYPE, LEARNING_TOPIC, LEARNING_DATE, LEARNING_LIKE)
VALUES (learning_id, 15, 'DIALOGUE', null, '{"place":"Library","assistantRole":"Librarian","userRole":"Student","situation":"I see a person struggling to carry a large stack of books.","option":"The person has a broken arm and cannot carry the books alone."}', SYSDATE, '0');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'Hello, how can I assist you today?', 'Oh, there is a person whose arm is broken and carrying the books alone. Can you help me to help him to carry the books?', 'Oh, there is a person with a broken arm who needs help carrying the books. Can you assist me in helping them?', 'I corrected the grammar and phrasing to make the message clearer and more concise. ''Whose arm is broken'' is changed to ''with a broken arm'' for clarity. ''Carrying the books alone'' is changed to ''needs help carrying the books'' to emphasize the need for assistance. Lastly, I added ''them'' to refer to the person with the broken arm instead of assuming their gender.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'Of course, I can help you both carry the books.', 'Okay, do you have any car to carry that many books?', 'Okay, do you have a car to help us carry all these books?', 'I corrected the sentence to make it more clear and concise. Also, I changed ''him'' to ''us'' to include yourself in the request for help. Additionally, I added ''all these'' to specify the number of books being carried.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'No, we don''t have a car, but we can provide a trolley to help carry the books.', 'yeah I meant the cart you you said the trolley yes it would be correct to call them crowd trolley let''s go help him', 'Yeah, I meant the cart. You said trolley, yes, it would be correct to call them crowd trolleys. Let''s go help him.', 'I corrected the capitalization and punctuation errors. Also, I added a missing word ''cart'' to make the sentence clearer. Additionally, I added a comma to separate the two independent clauses. Finally, I corrected the plural form of ''trolley'' to ''trolleys''.');
insert into sentence (ID, LEARNING_ID, SENTENCE_QUESTION, SENTENCE_ANSWER, SENTENCE_CORRECTED, SENTENCE_EXPLANATION)
VALUES (SENTENCE_ID_SEQ.nextval, learning_id, 'Sure, let''s go grab the trolley and help him out.', 'Yes, and I think you have to stand a card in your account that you are absent because of some jobs so that the other students do not be confused because of you not being here.', 'Yes, and I think you should update your account to indicate that you are absent due to work, so that other students are not confused by your absence.', 'I corrected the verb ''stand'' to ''update'' to make the sentence more clear and grammatically correct. I also added ''due to work'' to clarify the reason for the absence and changed ''do not be'' to ''are not'' to improve the sentence structure.');
